language: java
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: s3
  access_key_id: AKIAIQ7BLBMY4DQA2LNA
  secret_access_key:
    secure: tAKWv5UhlwszH13HYJpPQMwXCf2yY2/mrRL6KaA3kHccbN6pee7Two/qThuXAhGO0TveyckMnBoy7jX+A4S3J2zdQTbJKaSkeIfvfF+CWPm7eV83ZUY+7K/Phkwd6JhpFLweqx2VBvxaDMVdIqydimuulOhvyBJexNgv67xZt7fdauQyOpjDBHxPGx6UIcSLLS9mp5YNt8GJB53IPRwU4CwlKgKWqICkumn/dpsD9/bQiy6RM4lj5rgh3gaCJtBhv8bi624AMVv3LmU4z7/NJc/AtxMqmiansKzQahL8qxOgSd0IqNxb/HebddLa8q+vc02HxvhT/GSpjFlbrudKAaB7SZUEX3jiGL0ygAdqkxAfDoKuoIZ3lvECcJqicfVx3aoJUK5GoIpmtpn6Y3cD5cemzVOsNvc2hXaJfY369szkikzpUV191D6kv7Hz/7XNU92IRUNsxd+uRnwL3ngH5ah09bJvG2P8Y0j39TW9dbHWfIdYJosw3HFC4NnS7iW9LkhAefpvbvKAsKL/3KfjcZWna56v3cfQh92mKDS1sxIVU6ow2baWOyuQlydFaD90GlsGak+9230zy+YWxFC4CwbkGgMVDh1lJH7tMO+mvhT0PKyz2BMOhz+gauDxcRwqVNcYuENkrx8fmA+LJkvbaDyk02JOYekC/i8yjbLHn50=
  bucket: che4-target-platform
  skip_cleanup: true
  local_dir: target/repository
  acl: public_read
  region: eu-west-1
